import React from 'react'
import Head from 'next/head'
import styles from '../styles/Download.module.css'
import { Card } from 'react-bootstrap'

export default function download() {
  return (
    <>
    <Head>
        <title>Challenge 7 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"/>
      </Head>
    <div className={styles.container}>
      <h3>Your document is ready!</h3>
      <div className={styles.content}>
        <Card style={{ width: '18rem' }}>
          <Card.Img variant="top" src="/img/preview.png" />
          <Card.Body>
            <Card.Text><a href='/file.txt' download>Click here to download</a></Card.Text>
          </Card.Body>
          </Card>
      </div>
    </div>
    </>
  )
}
