import Head from "next/head"
import { Button } from "react-bootstrap"
import styles from '../styles/Input.module.css'

export default function input() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Challenge 7 App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"/>
      </Head>
      <div className={styles.inputForm}>
        <form action="/" method="post" className={styles.form}>
          <label for="name">Name</label>
          <input type="text" id="name" name="name" />
          <label for="age">Age</label>
          <input type="number" id="age" name="age" />
          <label for="email">Email</label>
          <input type="text" id="email" name="email" />
          <Button type="submit" className={styles.btn}>Submit</Button>
        </form>
      </div>
    </div>
  )
}
